# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ping_pong_dong.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14ping_pong_dong.proto\"\x1b\n\x0bPingRequest\x12\x0c\n\x04ping\x18\x01 \x01(\t\"\x19\n\tPongReply\x12\x0c\n\x04pong\x18\x01 \x01(\t25\n\x07Greeter\x12*\n\x0cPingPongDong\x12\x0c.PingRequest\x1a\n.PongReply\"\x00\x62\x06proto3')



_PINGREQUEST = DESCRIPTOR.message_types_by_name['PingRequest']
_PONGREPLY = DESCRIPTOR.message_types_by_name['PongReply']
PingRequest = _reflection.GeneratedProtocolMessageType('PingRequest', (_message.Message,), {
  'DESCRIPTOR' : _PINGREQUEST,
  '__module__' : 'ping_pong_dong_pb2'
  # @@protoc_insertion_point(class_scope:PingRequest)
  })
_sym_db.RegisterMessage(PingRequest)

PongReply = _reflection.GeneratedProtocolMessageType('PongReply', (_message.Message,), {
  'DESCRIPTOR' : _PONGREPLY,
  '__module__' : 'ping_pong_dong_pb2'
  # @@protoc_insertion_point(class_scope:PongReply)
  })
_sym_db.RegisterMessage(PongReply)

_GREETER = DESCRIPTOR.services_by_name['Greeter']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PINGREQUEST._serialized_start=24
  _PINGREQUEST._serialized_end=51
  _PONGREPLY._serialized_start=53
  _PONGREPLY._serialized_end=78
  _GREETER._serialized_start=80
  _GREETER._serialized_end=133
# @@protoc_insertion_point(module_scope)
